"""create_billing_tables

Revision ID: 282eb43ad43c
Revises: 9f4538e45b8d
Create Date: 2026-08-10 17:35:01.218101

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "282eb43ad43c"
down_revision: str | None = "9f4538e45b8d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The seeded "Default" plan row (final tiers/pricing aren't designed yet -
# see the `app/modules/billing/model.py` docstring for why
# `monthly_event_quota=None`/`is_default=True`). The ID is hardcoded
# (instead of the app runtime's `generate_uuid7()`) so this migration stays
# deterministic/repeatable across environments - UUID v7 is normally
# generated at the app level, and this migration is the one deliberate
# exception (seed data, not a row created through a normal application flow).
_DEFAULT_PLAN_ID = "019feb3d-a834-7e53-8675-ca1a187fedee"

_plans_table = sa.table(
    "plans",
    sa.column("id", sa.UUID()),
    sa.column("name", sa.String()),
    sa.column("monthly_event_quota", sa.Integer()),
    sa.column("price", sa.Numeric()),
    sa.column("is_default", sa.Boolean()),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plans",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("monthly_event_quota", sa.Integer(), nullable=True),
        sa.Column("price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plans")),
        sa.UniqueConstraint("name", name=op.f("uq_plans_name")),
    )
    op.create_table(
        "organization_plans",
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["plans.id"], name=op.f("fk_organization_plans_plan_id_plans")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
            name=op.f("fk_organization_plans_tenant_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization_plans")),
    )
    op.create_index(
        op.f("ix_organization_plans_plan_id"), "organization_plans", ["plan_id"], unique=False
    )
    op.create_index(
        op.f("ix_organization_plans_tenant_id"), "organization_plans", ["tenant_id"], unique=False
    )
    op.create_index(
        "uq_organization_plans_tenant_id_active",
        "organization_plans",
        ["tenant_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "usage_events",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.Enum("IN", "OUT", name="usage_event_type"), nullable=False),
        sa.Column("bot_id", sa.UUID(), nullable=False),
        sa.Column("destination_id", sa.UUID(), nullable=True),
        sa.Column("message_id", sa.UUID(), nullable=True),
        sa.Column("delivery_log_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], name=op.f("fk_usage_events_bot_id_bots")),
        sa.ForeignKeyConstraint(
            ["delivery_log_id"],
            ["delivery_logs.id"],
            name=op.f("fk_usage_events_delivery_log_id_delivery_logs"),
        ),
        sa.ForeignKeyConstraint(
            ["destination_id"],
            ["destinations.id"],
            name=op.f("fk_usage_events_destination_id_destinations"),
        ),
        sa.ForeignKeyConstraint(
            ["message_id"], ["messages.id"], name=op.f("fk_usage_events_message_id_messages")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
            name=op.f("fk_usage_events_tenant_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usage_events")),
    )
    op.create_index(op.f("ix_usage_events_bot_id"), "usage_events", ["bot_id"], unique=False)
    op.create_index(op.f("ix_usage_events_tenant_id"), "usage_events", ["tenant_id"], unique=False)
    op.create_index(
        "ix_usage_events_tenant_id_created_at",
        "usage_events",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_usage_events_tenant_id_event_type_created_at",
        "usage_events",
        ["tenant_id", "event_type", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Seed satu-satunya Plan MVP ini - lihat catatan `_DEFAULT_PLAN_ID` di atas.
    op.bulk_insert(
        _plans_table,
        [
            {
                "id": _DEFAULT_PLAN_ID,
                "name": "Default",
                "monthly_event_quota": None,
                "price": None,
                "is_default": True,
            }
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_usage_events_tenant_id_event_type_created_at", table_name="usage_events")
    op.drop_index("ix_usage_events_tenant_id_created_at", table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_tenant_id"), table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_bot_id"), table_name="usage_events")
    op.drop_table("usage_events")
    op.drop_index(
        "uq_organization_plans_tenant_id_active",
        table_name="organization_plans",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_organization_plans_tenant_id"), table_name="organization_plans")
    op.drop_index(op.f("ix_organization_plans_plan_id"), table_name="organization_plans")
    op.drop_table("organization_plans")
    op.drop_table("plans")
    # The `usage_event_type` Postgres enum type is NOT automatically
    # dropped by `drop_table` (same fix as in the `bots`/`destinations`/
    # `messaging` migrations) - dropped explicitly here so a repeated
    # `upgrade`/`downgrade`/`upgrade` doesn't collide with "type already exists".
    sa.Enum(name="usage_event_type").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
