"""create bot_assignments table

Revision ID: 2c5141f25fd2
Revises: d9565845dd35
Create Date: 2026-08-10 21:53:28.964449

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c5141f25fd2"
down_revision: str | None = "d9565845dd35"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_assignments",
        sa.Column("bot_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["bots.id"], name=op.f("fk_bot_assignments_bot_id_bots")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
            name=op.f("fk_bot_assignments_tenant_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_bot_assignments_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_assignments")),
    )
    op.create_index(op.f("ix_bot_assignments_bot_id"), "bot_assignments", ["bot_id"], unique=False)
    op.create_index(
        op.f("ix_bot_assignments_tenant_id"), "bot_assignments", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_bot_assignments_tenant_id_bot_id",
        "bot_assignments",
        ["tenant_id", "bot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bot_assignments_user_id"), "bot_assignments", ["user_id"], unique=False
    )
    op.create_index(
        "uq_bot_assignments_bot_id_user_id_active",
        "bot_assignments",
        ["bot_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_bot_assignments_bot_id_user_id_active",
        table_name="bot_assignments",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(op.f("ix_bot_assignments_user_id"), table_name="bot_assignments")
    op.drop_index("ix_bot_assignments_tenant_id_bot_id", table_name="bot_assignments")
    op.drop_index(op.f("ix_bot_assignments_tenant_id"), table_name="bot_assignments")
    op.drop_index(op.f("ix_bot_assignments_bot_id"), table_name="bot_assignments")
    op.drop_table("bot_assignments")
    # ### end Alembic commands ###
