"""create_bots_table

Revision ID: 3a244f8916f4
Revises: 4a41596b8564
Create Date: 2026-08-10 14:27:36.751272

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3a244f8916f4"
down_revision: str | None = "4a41596b8564"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bots",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("telegram_bot_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("webhook_secret", sa.String(length=255), nullable=False),
        sa.Column("webhook_enabled", sa.Boolean(), nullable=False),
        sa.Column("api_key_hash", sa.String(length=64), nullable=False),
        sa.Column("api_key_prefix", sa.String(length=20), nullable=False),
        sa.Column("outbound_callback_url", sa.String(length=2048), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["organizations.id"], name=op.f("fk_bots_tenant_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bots")),
        sa.UniqueConstraint("api_key_hash", name="uq_bots_api_key_hash"),
    )
    op.create_index(op.f("ix_bots_tenant_id"), "bots", ["tenant_id"], unique=False)
    op.create_index(
        "ix_bots_tenant_id_created_at", "bots", ["tenant_id", "created_at"], unique=False
    )
    op.create_index(
        "uq_bots_telegram_bot_id_active",
        "bots",
        ["telegram_bot_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_bots_telegram_bot_id_active",
        table_name="bots",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_bots_tenant_id_created_at", table_name="bots")
    op.drop_index(op.f("ix_bots_tenant_id"), table_name="bots")
    op.drop_table("bots")
    # ### end Alembic commands ###
