"""create messaging tables

Revision ID: 9f4538e45b8d
Revises: e559793a7a78
Create Date: 2026-08-10 15:39:30.130270

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f4538e45b8d"
down_revision: str | None = "e559793a7a78"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_templates",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "parse_mode", sa.Enum("HTML", "MARKDOWN_V2", name="message_parse_mode"), nullable=True
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
            name=op.f("fk_message_templates_tenant_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_templates")),
    )
    op.create_index(
        op.f("ix_message_templates_tenant_id"), "message_templates", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_message_templates_tenant_id_created_at",
        "message_templates",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("bot_id", sa.UUID(), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=True),
        sa.Column(
            "content_type",
            sa.Enum("TEXT", "MEDIA", "POLL", name="message_content_type"),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column(
            "parse_mode", sa.Enum("HTML", "MARKDOWN_V2", name="message_parse_mode"), nullable=True
        ),
        sa.Column(
            "media_type",
            sa.Enum("PHOTO", "DOCUMENT", "VIDEO", name="message_media_type"),
            nullable=True,
        ),
        sa.Column("media_url", sa.String(length=2048), nullable=True),
        sa.Column("inline_keyboard", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("poll", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], name=op.f("fk_messages_bot_id_bots")),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["message_templates.id"],
            name=op.f("fk_messages_template_id_message_templates"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["organizations.id"], name=op.f("fk_messages_tenant_id_organizations")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
    )
    op.create_index(op.f("ix_messages_bot_id"), "messages", ["bot_id"], unique=False)
    op.create_index(
        "ix_messages_scheduled_at_dispatched_at",
        "messages",
        ["scheduled_at", "dispatched_at"],
        unique=False,
    )
    op.create_index(op.f("ix_messages_tenant_id"), "messages", ["tenant_id"], unique=False)
    op.create_index(
        "ix_messages_tenant_id_bot_id", "messages", ["tenant_id", "bot_id"], unique=False
    )
    op.create_index(
        "ix_messages_tenant_id_created_at", "messages", ["tenant_id", "created_at"], unique=False
    )
    op.create_table(
        "delivery_logs",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("destination_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("QUEUED", "SENT", "FAILED", name="delivery_log_status"),
            nullable=False,
        ),
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=True),
        sa.Column("error_reason", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["destination_id"],
            ["destinations.id"],
            name=op.f("fk_delivery_logs_destination_id_destinations"),
        ),
        sa.ForeignKeyConstraint(
            ["message_id"], ["messages.id"], name=op.f("fk_delivery_logs_message_id_messages")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
            name=op.f("fk_delivery_logs_tenant_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_delivery_logs")),
        sa.UniqueConstraint(
            "message_id", "destination_id", name="uq_delivery_logs_message_id_destination_id"
        ),
    )
    op.create_index(
        op.f("ix_delivery_logs_destination_id"), "delivery_logs", ["destination_id"], unique=False
    )
    op.create_index(
        op.f("ix_delivery_logs_message_id"), "delivery_logs", ["message_id"], unique=False
    )
    op.create_index(
        op.f("ix_delivery_logs_tenant_id"), "delivery_logs", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_delivery_logs_tenant_id_created_at",
        "delivery_logs",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_delivery_logs_tenant_id_status", "delivery_logs", ["tenant_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_delivery_logs_tenant_id_status", table_name="delivery_logs")
    op.drop_index("ix_delivery_logs_tenant_id_created_at", table_name="delivery_logs")
    op.drop_index(op.f("ix_delivery_logs_tenant_id"), table_name="delivery_logs")
    op.drop_index(op.f("ix_delivery_logs_message_id"), table_name="delivery_logs")
    op.drop_index(op.f("ix_delivery_logs_destination_id"), table_name="delivery_logs")
    op.drop_table("delivery_logs")
    op.drop_index("ix_messages_tenant_id_created_at", table_name="messages")
    op.drop_index("ix_messages_tenant_id_bot_id", table_name="messages")
    op.drop_index(op.f("ix_messages_tenant_id"), table_name="messages")
    op.drop_index("ix_messages_scheduled_at_dispatched_at", table_name="messages")
    op.drop_index(op.f("ix_messages_bot_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_message_templates_tenant_id_created_at", table_name="message_templates")
    op.drop_index(op.f("ix_message_templates_tenant_id"), table_name="message_templates")
    op.drop_table("message_templates")
    # ### end Alembic commands ###
    # Autogenerate doesn't drop custom Postgres enum types (`sa.Enum`) -
    # this must be explicit, or the next upgrade fails with "type already
    # exists" (same note as migration `4a41596b8564`/`e559793a7a78`).
    sa.Enum(name="delivery_log_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="message_media_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="message_content_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="message_parse_mode").drop(op.get_bind(), checkfirst=True)
