"""create_destinations_and_bot_destination_subscriptions_tables

Revision ID: e559793a7a78
Revises: 3a244f8916f4
Create Date: 2026-08-10 14:47:58.666728

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e559793a7a78"
down_revision: str | None = "3a244f8916f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "destinations",
        sa.Column(
            "type",
            sa.Enum("PERSONAL", "GROUP", "GROUP_THREAD", "CHANNEL", name="destination_type"),
            nullable=False,
        ),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("thread_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
            name=op.f("fk_destinations_tenant_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_destinations")),
    )
    op.create_index(op.f("ix_destinations_tenant_id"), "destinations", ["tenant_id"], unique=False)
    op.create_index(
        "ix_destinations_tenant_id_created_at",
        "destinations",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_destinations_chat_active",
        "destinations",
        ["tenant_id", "chat_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND thread_id IS NULL"),
    )
    op.create_index(
        "uq_destinations_chat_thread_active",
        "destinations",
        ["tenant_id", "chat_id", "thread_id"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL AND thread_id IS NOT NULL"),
    )
    op.create_table(
        "bot_destination_subscriptions",
        sa.Column("bot_id", sa.UUID(), nullable=False),
        sa.Column("destination_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "UNSUBSCRIBED",
                "BLOCKED_BY_ADMIN",
                name="bot_destination_subscription_status",
            ),
            nullable=False,
        ),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["bot_id"], ["bots.id"], name=op.f("fk_bot_destination_subscriptions_bot_id_bots")
        ),
        sa.ForeignKeyConstraint(
            ["destination_id"],
            ["destinations.id"],
            name=op.f("fk_bot_destination_subscriptions_destination_id_destinations"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["organizations.id"],
            name=op.f("fk_bot_destination_subscriptions_tenant_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_destination_subscriptions")),
        sa.UniqueConstraint(
            "bot_id",
            "destination_id",
            name="uq_bot_destination_subscriptions_bot_id_destination_id",
        ),
    )
    op.create_index(
        op.f("ix_bot_destination_subscriptions_bot_id"),
        "bot_destination_subscriptions",
        ["bot_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bot_destination_subscriptions_destination_id"),
        "bot_destination_subscriptions",
        ["destination_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bot_destination_subscriptions_tenant_id"),
        "bot_destination_subscriptions",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_bot_destination_subscriptions_tenant_id_bot_id",
        "bot_destination_subscriptions",
        ["tenant_id", "bot_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_bot_destination_subscriptions_tenant_id_bot_id",
        table_name="bot_destination_subscriptions",
    )
    op.drop_index(
        op.f("ix_bot_destination_subscriptions_tenant_id"),
        table_name="bot_destination_subscriptions",
    )
    op.drop_index(
        op.f("ix_bot_destination_subscriptions_destination_id"),
        table_name="bot_destination_subscriptions",
    )
    op.drop_index(
        op.f("ix_bot_destination_subscriptions_bot_id"), table_name="bot_destination_subscriptions"
    )
    op.drop_table("bot_destination_subscriptions")
    op.drop_index(
        "uq_destinations_chat_thread_active",
        table_name="destinations",
        postgresql_where=sa.text("deleted_at IS NULL AND thread_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_destinations_chat_active",
        table_name="destinations",
        postgresql_where=sa.text("deleted_at IS NULL AND thread_id IS NULL"),
    )
    op.drop_index("ix_destinations_tenant_id_created_at", table_name="destinations")
    op.drop_index(op.f("ix_destinations_tenant_id"), table_name="destinations")
    op.drop_table("destinations")
    # ### end Alembic commands ###
    # Autogenerate doesn't drop custom Postgres enum types (`sa.Enum`) -
    # this must be explicit, or the next upgrade fails with "type already
    # exists" (same note as in migration `4a41596b8564`).
    sa.Enum(name="bot_destination_subscription_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="destination_type").drop(op.get_bind(), checkfirst=True)
